# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'vista_audio.ui'
#
# Created by: PyQt5 UI code generator 5.15.6
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(547, 224)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.pushButton_Adelante = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_Adelante.setGeometry(QtCore.QRect(60, 70, 131, 51))
        self.pushButton_Adelante.setStyleSheet("font: 75 20pt \"MS Shell Dlg 2\";")
        self.pushButton_Adelante.setObjectName("pushButton_Adelante")
        self.label = QtWidgets.QLabel(self.centralwidget)
        self.label.setGeometry(QtCore.QRect(10, 10, 531, 31))
        self.label.setStyleSheet("font: 75 20pt \"MS Shell Dlg 2\";")
        self.label.setObjectName("label")
        self.pushButton_Atras = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_Atras.setGeometry(QtCore.QRect(120, 130, 131, 51))
        self.pushButton_Atras.setStyleSheet("font: 75 20pt \"MS Shell Dlg 2\";")
        self.pushButton_Atras.setObjectName("pushButton_Atras")
        self.pushButton_Izquierda = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_Izquierda.setGeometry(QtCore.QRect(210, 70, 131, 51))
        self.pushButton_Izquierda.setStyleSheet("font: 75 20pt \"MS Shell Dlg 2\";")
        self.pushButton_Izquierda.setObjectName("pushButton_Izquierda")
        self.pushButton_Alto = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_Alto.setGeometry(QtCore.QRect(280, 130, 131, 51))
        self.pushButton_Alto.setStyleSheet("font: 75 20pt \"MS Shell Dlg 2\";")
        self.pushButton_Alto.setObjectName("pushButton_Alto")
        self.pushButton_Derecha = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_Derecha.setGeometry(QtCore.QRect(360, 70, 131, 51))
        self.pushButton_Derecha.setStyleSheet("font: 75 20pt \"MS Shell Dlg 2\";")
        self.pushButton_Derecha.setObjectName("pushButton_Derecha")
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 547, 21))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.pushButton_Adelante.setText(_translate("MainWindow", "Adelante"))
        self.label.setText(_translate("MainWindow", "Grabar Audio para los siguientes comandos:"))
        self.pushButton_Atras.setText(_translate("MainWindow", "Atras"))
        self.pushButton_Izquierda.setText(_translate("MainWindow", "Izquierda"))
        self.pushButton_Alto.setText(_translate("MainWindow", "Alto"))
        self.pushButton_Derecha.setText(_translate("MainWindow", "Derecha"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())
